spring.application.name=qorifit

server.port=${SPRING_PORT:9011}

server.servlet.context-path=${SPRING_CONTEXT_PATH:/api/qorifit}

spring.datasource.url=${DB_URL:jdbc:postgresql://db.omffgfcvulszlqdehrxh.supabase.co:5432/postgres?user=postgres&password=schrodingercat159@}
spring.datasource.username= ${DB_USERNAME:postgres}
spring.datasource.password= ${DB_PASSWORD:schrodingercat159@}

security.jwt.key.private = ${JWT_PRIVATE_KEY:db41f1098f6cde14f8c711249cfdf9e8222418fba9d70e47c37f9e35219e9d53}
security.jwt.user.generator = ${JWT_PUBLIC_KEY:*Lifox404*}
jwt.access-token-expiration= ${PERMISSION_EXPIRATION:18000000}
spring.security.user.password=none

spring.datasource.hikari.pool-name=PostgreSQLPool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=1800000
spring.datasource.hikari.max-lifetime=7200000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=0
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.register-mbeans=true
spring.datasource.hikari.leak-detection-threshold=0

#spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=none


spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

